package com.sturdy.sturdymem.service;

import com.sturdy.sturdymem.dao.MyRepository;
import com.sturdy.sturdymem.dao.MyTransactionRepository;
import com.sturdy.sturdymem.entity.MyTransactionResource;
import com.sturdy.sturdymem.util.SturdyHelper;
import org.bson.types.ObjectId;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class SturdyMemServiceImpl implements SturdyMemService {

    private Logger logger = LoggerFactory.getLogger(SturdyHelper.class);

    @Autowired
    private MyRepository myRepository;

    @Autowired
    private MyTransactionRepository myTransactionRepository;

    //TODO Revisit mongoTemplate. As of now all CRUD operations are taken care of by Repository Classes.
    //@Autowired
    //private MongoTemplate mongoTemplate;

    //TODO Revisit saveToDictionary

    //TODO Will revisit findIfTargetWordExists(String targetWord) and saveMyTransaction(MyTransactionResource myTransactionResource later.
    // @Sid:Dec 14: this commented code is also removed . @Vinod - Pls revert, if any.
    @Override
    public boolean saveMyTransaction(MyTransactionResource myTransactionResource) {
        MyTransactionResource myTransactionResource1 = myTransactionRepository.save(myTransactionResource);
        return true;
    }

    @Override
    public MyTransactionResource fetchTransactionByTransId(String transId) {
        return myTransactionRepository.getByTransId(transId);
    }

    /**
     * Fetch transaction based on primary key _id (AutoGenerated by MongoDB)
     * TODO Refactor based on data model
     */
    @Override
    public MyTransactionResource fetchTransactionById(ObjectId id) {
        return myTransactionRepository.findById(id).orElse(null);
    }

    //TODO Will add update later.
    @Override
    public boolean updateMyTransaction(String transId, MyTransactionResource myTransactionResource) {
        myTransactionRepository.save(myTransactionResource);
        return true; //todo change this to conditional
    }
}
